language:
  - python
before-install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
script: 
  - python manage.py migrate
  - flake8 --max-line-length=92
  - black --check .
after_script:
  - coveralls

